name: Xfe Document CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.checkCommitMessage.conclusion }}
    steps: 
      - name: checkCommitMessage
        if: startsWith(github.event.head_commit.message, 'release:') != true
        run: |
          echo "commit message 中没有使用 ‘release:’ 开头故终止当前 CI."
          exit
          
  build:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.status == 'success'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and Build
        run: yarn install && yarn docs:build

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v2
        with: 
          build_dir: docs/.vuepress/dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
