name: Xfe Document CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and Build
        run: yarn install && yarn docs:build

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v2
        if: startsWith(github.event.head_commit.message, 'release:')
        with: 
          build_dir: docs/.vuepress/dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
